### ISSUE TITLE
Text in header is not well readable on RTD

### ISSUE THREAD

**Issue by christian-herber-nxp** [openhwgroup/core-v-xif#129]
![image](https://github.com/openhwgroup/core-v-xif/assets/101172126/65dc10db-94ee-46b4-876d-a7754cc80529)
Top left, the text is not well readable. This includes the short title at the top, but especially the version number. Background is that we are using the read the docs template. This has a blue background where in the OpenHW Group documents it is overridden with grey. With the blue background, the logo would look bad. With grey background, you have grey text on grey background. I am pretty sure this could be fixed through css (e.g. making the text black), but my css knowledge is insufficient. Long term solution would be to have an OpenHW group template.

**Comment by MikeOpenHWGroup** [comment]
Nice! Thanks @christian-herber-nxp
