### ISSUE TITLE
CV-X-IF vs. CORE-V-XIF

### ISSUE THREAD

**Issue by ASintzoff** [openhwgroup/core-v-xif#138]
In https://github.com/openhwgroup/core-v-xif/pull/124/commits/8d7a432ceaca51b62af772b449af29e26120ad02 the term `CORE-V-XIF` is replaced by `CV-X-IF` in `README.md` and `intro.rst` files.

Is there any reason to keep `CORE-V-XIF` in `x_ext.rst` file? For the sake of consistency, it would be preferable to use only one acronym.

**Comment by christian-herber-nxp** [comment]
You are right. This is a leftover. I think we really have established CV-X-IF as the nominal abbreviation
