### ISSUE TITLE
Unrelated reference to mode signal 

### ISSUE THREAD

**Issue by ASintzoff** [openhwgroup/core-v-xif#140]
At https://github.com/openhwgroup/core-v-xif/blob/85696cdacb977aa7e054985c4c630db6bb12e019/docs/source/x_ext.rst#L423 there is a reference to ``mode`` signal which does not exist when memory interface is not supported.

It would be better to remove this reference as the current generated PDF file does not provide information about this signal.

**Comment by christian-herber-nxp** [comment]
good catch. Will change that.
