### ISSUE TITLE
Clarification of valid-ready handshake dependency

### ISSUE THREAD

**Issue by flegert** [openhwgroup/core-v-xif#145]
The manual states:
 
> 4.9 Handshake dependencies
> ...
> The valid signal of a transaction shall not be dependent on the corresponding ready signal.
> ...
> Note: The use of the words depend and dependent relate to logical relationships, ...
 
However, as I understand it, in some way each valid signal has to be logically dependent on the ready signal. For example, a coprocessor generating a result transaction would set result_valid = 1, keep it high until CPU sets result_ready = 1, and then resets result_valid = 0 in the following cycle i no further instruction is processed at the moment.

Maybe it would help to define what "logically dependent" exactly means in this context?

**Comment by christian-herber-nxp** [comment]
@Silabs-ArjanB I think your input would be valuable here.
I agree that there should actually be a logical relationship, in a sense that the deassertion of ``valid`` may be a consequence of the assertion of ``ready``. I would assume that by logical relationships both combinatorial and sequential logic relationships are meant

**Comment by Silabs-ArjanB** [comment]
The requirement is for 1 transaction. The supposed counter example given above is about 2 transactions.

**Comment by flegert** [comment]
You are right, I missed the transaction constraint! Apologies for the oversight, given this I would suggest closing the issue.
