### ISSUE TITLE
Long lived URL

### ISSUE THREAD

**Issue by jquevremont** [openhwgroup/core-v-xif#159]
In section 5.3, the link to [CV32E40X eXtension timing budget](https://cv32e40x-user-manual.readthedocs.io/en/latest/x_ext.html#timing) may change in the future, especially because it is an active project.

Therefore my suggestion is to copy the image in the document, or alternatively point to a long-lived GitHub URL.

The URL https://github.com/openhwgroup/core-v-verif/tree/master/lib/uvm_agents/uvma_cvxif could have the same issue if the repository is re-organized. I have no easy suggestion for it.

**Comment by christian-herber-nxp** [comment]
I will take the last known good commit hash to make these robust. If there are production releases, would be good to update to tagged versions.
