### ISSUE TITLE
Confused by X_MISA text

### ISSUE THREAD

**Issue by jquevremont** [openhwgroup/core-v-xif#175]
When reading the ``X_MISA`` description, I am a bit confused.

The specification states:

> MISA extensions implemented on the eXtension interface.

So I could understand that the value is defined based on the extension(s) provided by the coprocessor.

But the document also states:

> The CPU determines the legal values for this parameter.

So I could understand that the value is defined based on the extension(s) supported natively supported by the processor.

Could you clarify? An example could help (e.g. an RV32IMAC core extended a coprocessor supporting the F extension). A second example could illustrate a custom extension.

My expectation is that ``X_MISA`` encodes the extension(s) provided by the coprocessor and that the processor will logically OR it with its own ``MISA``.

**Comment by christian-herber-nxp** [comment]
did you check https://github.com/openhwgroup/core-v-xif/issues/69?
