### ISSUE TITLE
exc, excode, dbg and err still present

### ISSUE THREAD

**Issue by pascalgouedo** [openhwgroup/core-v-xif#183]
Even if this issue #151 is marked as merged and closed with PR #152 those 4 signals are still in v1.0.0-rc.1.

I completely understand that dbg and err should be moved to Memory interface.

But I don't get the point of moving exc/exccode as well.
I think any non-memory instruction should be able to report an exception related to its own architectural definition if wanted.

### Proposed resolution

Remove dbg and err.

Explain how to signal exceptions to the CPU if exc* are moved to Memory interface.

**Comment by pascalgouedo** [comment]
What about exc/exccode? Still moved to memory interface?
If local XS is off, how to answer with illegal instruction error without memory interface?

**Comment by christian-herber-nxp** [comment]
By not accepting the instruction. Then nobody will accept it an an illegal instruction trap will happen. But maybe that's a fair point to put into the spec explicitly
