### ISSUE TITLE
[Review Comment]: Compressed itf only for compressed instructions

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/core-v-xif#201]
### Comment

![image](https://github.com/openhwgroup/core-v-xif/assets/40633348/bb999418-9c18-40ee-b338-f6905bda7ccb)

### Proposed Resolution

See above

**Comment by christian-herber-nxp** [comment]
did we not discuss this in one of the meetings and concluded it was not necessary to put such a restriction into the spec?

**Comment by Silabs-ArjanB** [comment]
I forgot the conclusion and I don't think it matters much, but we need to make either choice explicit (I don't care what choice)

**Comment by christian-herber-nxp** [comment]
as the coprocessor has to anyway inspect the LSBs, I would put the requirement on the copro. At the same time, the CPU will likely anyway be aware of the instruction length, as it has to obtain 16B from the prefetch buffer. But putting the restriction on the copro is I think the smaller restriction
