### ISSUE TITLE
[Review Comment]: Unclarity related to acceptance

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/core-v-xif#203]
### Comment

![image](https://github.com/openhwgroup/core-v-xif/assets/40633348/8dcddcf7-282f-4544-b44a-db153f2abbd6)

### Proposed Resolution

See above

**Comment by christian-herber-nxp** [comment]
this is already fixed. please check if the resolution in the latest version is sufficient. If yes, close this issue

**Comment by Silabs-ArjanB** [comment]
Text still looks the same to me in the current repos

**Comment by christian-herber-nxp** [comment]
I added a the new text, but forgot to remove the old. will fix.
