### ISSUE TITLE
Clarify err - NMI interaction

### ISSUE THREAD

**Issue by Silabs-ArjanB** [openhwgroup/core-v-xif#23]
Bus errors are signaled to the coprocessor for offloaded loads/stores via the err signal (see https://docs.openhwgroup.org/projects/openhw-group-core-v-xif/x_ext.html#memory-result-interface). It is also stated that NMI is signaled for such bus errors. It is the intention that the processor (as opposed to the coprocessor) signals the NMI, but this is not explicitly stated. Maybe NMIs should not even be mandated, but only allowed (such that the processor can itself decide how it wants to handle bus errors (precise or imprecise).

**Comment by christian-herber-nxp** [comment]
I would expect NMIs to be used for more serious situations. RISC-V has dedicated exception code for load and store errors, so I would expect a CPU to raise those.
