### ISSUE TITLE
a killed instruction can not signal a synchronous exception

### ISSUE THREAD

**Issue by ZElkacimi** [openhwgroup/core-v-xif#46]
"A synchronous exception will lead to a trap in CPU **unless the corresponding instruction is killed**" how can a killed instruction signal a synchronous exception? knowing that there is no result for killed instructions.
 @silabs-robin

**Comment by Silabs-ArjanB** [comment]
Hi @ZElkacimi The 'unless' part is not needed indeed (it was there due to a copy/paste error). Can you check if https://github.com/openhwgroup/core-v-xif/pull/47 fixed this please?

**Comment by ZElkacimi** [comment]
Hello @Silabs-ArjanB Yes it's fixed, thank you.
