### ISSUE TITLE
Should the parameters be signed?

### ISSUE THREAD

**Issue by bertwhl** [openhwgroup/core-v-xif#55]
Hello,
I have noticed that many parameters in the standard are 'int' instead of 'unsigned int'. Since the legal values of these parameters are all positive integers, I think the parameters does not need to be signed int.

**Comment by Silabs-ArjanB** [comment]
Hi @bertwhl Agreed, I think that should get fixed.

**Comment by Silabs-ArjanB** [comment]
@bertwhl Could you please have a look if https://github.com/openhwgroup/core-v-xif/pull/60 fixes this issue?

**Comment by bertwhl** [comment]
Thank you for the reply and update!
