### ISSUE TITLE
Writeback to x0

### ISSUE THREAD

**Issue by moimfeld** [openhwgroup/core-v-xif#58]
Hi @Silabs-ArjanB,

In both the "F" and "V" RISC-V standard extensions there exist instructions (e.g. `vset{i}vl{i} rd, {...}`, ` csrrw rd, fcsr, rs`) that will write back to the general purpose register file only if `rd != x0`. Is it allowed for a coprocessor to assert `writeback` in the issue transaction and `we` in the result transaction even if `rd == x0`? Or more general, should a core be able to ignore writebacks to x0 (and associated signals) in general?

I know from @michael-platzer that in Vicuna `writeback` and `we` are asserted even if `rd == x0`. The same is true for the floating-point coprocessor I developed a while ago.

**Comment by Silabs-ArjanB** [comment]
Hi @moimfeld, a coprocessor is allowed t oassert writeback and we if rd = x0. The core shall then ignore the writeback. There is an old pull request (I don't know why it has not been merged yet) to mandate even stronger behavior related to the P extension, see https://github.com/openhwgroup/core-v-xif/pull/57.

Let make it explicit in the document that:

- coprocessor is allowed to signal writeback and we when rd == x0
- processor shall ignore writebacks to x0

Okay?

**Comment by moimfeld** [comment]
Hi @Silabs-ArjanB 

PR #60 does indeed fix this issue, thank you! I will close this issue once the PR is merged.
