### ISSUE TITLE
Contradictory requirements for result signal stability

### ISSUE THREAD

**Issue by moimfeld** [openhwgroup/core-v-xif#61]
Hi @Silabs-ArjanB 

The lines below seem to contradict each other. First it says, all `result` signals **except** `data` must be stable (data must only be stable if `we` is not 0 during the result transaction) and in line 892 it says the `result` signals should remain stable, which implies that all `result` signals (including `data`) should remain stable.

One could remove the second sentence of line 892 to resolve this contradiction.

https://github.com/openhwgroup/core-v-xif/blob/78a2907c62f4b3085df9e09cae732e8d3fe48a88/docs/source/x_ext.rst#L866-L868

https://github.com/openhwgroup/core-v-xif/blob/78a2907c62f4b3085df9e09cae732e8d3fe48a88/docs/source/x_ext.rst#L892

Additionally, one could remove the stability condition for the `ecsdata` signal, if the corresponding `ecswe` field is low.

Let me know what you think. I can also create a PR if you agree with these changes.

Best
Moritz

**Comment by Silabs-ArjanB** [comment]
Hello @moimfeld , this is not correct indeed. I would prefer if simply the part that states ', except that data is only required to remain stable during result transactions in which we is not 0.' would be removed. Is that okay with you? If so, just make a PR and let Davide know.
