### ISSUE TITLE
Missing image for building documentation

### ISSUE THREAD

**Issue by christian-herber-nxp** [openhwgroup/core-v-xif#74]
I tried running the build, but i am getting the following:

```
WARNING: logo file '../images/openhw-landscape.svg' does not exist
```

I assume that some assumption is being made that a user will have this image provided at the given location. I think it would be very reasonable to put a copy of the logo into the repository to make it self-contained

**Comment by MikeOpenHWGroup** [comment]
Hi @christian-herber-nxp.  I am not the right member of the OpenHW staff drive development of this repo.  I have experience with ReStructured Text, Sphinx and ReadTheDocs, so I can offer assistance to anyone who would like to drive this repo.

**Comment by christian-herber-nxp** [comment]
fixed
