### ISSUE TITLE
Reduce the focus of the core-v-xif project 1.0 to the X-interface (core to/from co-processor)

### ISSUE THREAD

**Issue by davideschiavone** [openhwgroup/core-v-xif#8]
The current spec specifies what happens between the core and the adapter (X-if) and between the adapter and the co-processor (C-if).

We shall limit the spec between the core and the co-processor and move to an "example folder" the adapter implementation/specification together with the C-if for multiple co-processor implementations.

**Comment by davideschiavone** [comment]
shall we close this issue @Silabs-ArjanB ?

**Comment by Silabs-ArjanB** [comment]
Yes

**Comment by davideschiavone** [comment]
fixed by https://github.com/openhwgroup/core-v-xif/commit/0772c25f294fae1a9c96153a6237fcf103565374
